import type { Metadata } from "next";
import { Inter,  Poppins} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({weight: "400", subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <html lang="en">
        <body className={poppins.className}>
          <ThemeProvider
              themes={["light", "dark"]}
              defaultTheme="dark"
              attribute="class"
              enableSystem
              disableTransitionOnChange
            >
          {children}
          </ThemeProvider>
        </body>
      </html>
  );
}
